project:
  type: website
  output-dir: _site

website:
  title: "Classification du vin"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: dataset.qmd
        text: Jeu de données
      - href: classification.qmd
        text: Méthodes de classification
      - href: resultats.qmd
        text: Comparaison des modèles
